### ISSUE TITLE
question about the installation of cuda

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#10]
HI,
  I am planning to install the `cuda`  as described  in the github on my ubuntu 18.04.4 , but it tells 

> The driver installation is unable to locate the kernel source,Please make sure that the kernel source packages are installed and set up correctly.
If you know that the kernel source packages are installed and set up correctly, you may pass the location of the kernel source with the '--kernel-source-path' flag.

so how can get it installed ?

**Comment by longzhangnation** [comment]
here is the log file .

> Installing the NVIDIA display driver...
Verifying archive integrity... OK

Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 410.48................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................



WARNING: You do not appear to have an NVIDIA GPU supported by the 410.48

         NVIDIA Linux graphics driver installed in this system.  For

         further details, please see the appendix SUPPORTED NVIDIA GRAPHICS

         CHIPS in the README available on the Linux driver download page at

         www.nvidia.com.





Welcome to the NVIDIA Software Installer for Unix/Linux



Detected 128 CPUs online; setting concurrency level to 32.

Installing NVIDIA driver version 410.48.

Running distribution scripts

  Executing /usr/lib/nvidia/pre-install: [##############################] 100%



WARNING: One or more modprobe configuration files to disable Nouveau are

         already present at:

         /etc/modprobe.d/nvidia-installer-disable-nouveau.conf.  Please be

         sure you have rebooted your system since these files were written.

         If you have rebooted, then Nouveau may be enabled for other

         reasons, such as being included in the system initial ramdisk or

         in your X configuration file.  Please consult the NVIDIA driver

         README and your Linux distribution's documentation for details on

         how to correctly disable the Nouveau kernel driver.



The distribution-provided pre-install script failed!  Are you sure you want

to continue? (Answer: Continue installation)

For some distributions, Nouveau can be disabled by adding a file in the

modprobe configuration directory.  Would you like nvidia-installer to

attempt to create this modprobe file for you? (Answer: Yes)



One or more modprobe configuration files to disable Nouveau have been

written.  For some distributions, this may be sufficient to disable

Nouveau; other distributions may require modification of the initial

ramdisk.  Please reboot your system and attempt NVIDIA driver installation

again.  Note if you later wish to reenable Nouveau, you will need to delete

these files: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf



Performing CC sanity check with CC="/usr/bin/cc".

Using the kernel source path '/lib/modules/4.15.0-74-generic/build' as

specified by the '--kernel-source-path' commandline option.

Kernel source path: '/lib/modules/4.15.0-74-generic/build'

Kernel output path: '/lib/modules/4.15.0-74-generic/build'

Performing Compiler check.

Performing Dom0 check.

Performing Xen check.

Performing PREEMPT_RT check.

Performing vgpu_kvm check.

Cleaning kernel module build directory.

Building kernel modules

  : [##############################] 100%



ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most

       frequently when this kernel module was built against the wrong or

       improperly configured kernel sources, with a version of gcc that

       differs from the one used to build the target kernel, or if another

       driver, such as nouveau, is present and prevents the NVIDIA kernel

       module from obtaining ownership of the NVIDIA GPU(s), or no NVIDIA

       GPU installed in this system is supported by this NVIDIA Linux

       graphics driver release.



       Please see the log entries 'Kernel module load error' and 'Kernel

       messages' at the end of the file '/var/log/nvidia-installer.log' for

       more information.





ERROR: Installation has failed.  Please see the file

       '/var/log/nvidia-installer.log' for details.  You may find

       suggestions on fixing installation problems in the README available

       on the Linux driver download page at www.nvidia.com.



Kernel module compilation complete.

Kernel module load error: No such device

Kernel messages:

[5344899.243504] audit: type=1400 audit(1588632202.436:472):

apparmor="STATUS" operation="profile_replace" info="same as current

profile, skipping" profile="unconfined" name="/usr/sbin/mysqld" pid=93394

comm="apparmor_parser"

[5344899.294327] audit: type=1400 audit(1588632202.488:473):

apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld"

name="/usr/local/lib/libgcc_s.so.1" pid=93412 comm="mysqld"

requested_mask="r" denied_mask="r" fsuid=0 ouid=0

[5366581.585458] VFIO - User Level meta-driver version: 0.3

[5366581.689080] nvidia: loading out-of-tree module taints kernel.

[5366581.689094] nvidia: module license 'NVIDIA' taints kernel.

[5366581.689095] Disabling lock debugging due to kernel taint

[5366581.697791] nvidia: module verification failed: signature and/or

required key missing - tainting kernel

[5366581.707649] nvidia-nvlink: Nvlink Core is being initialized, major

device number 237

[5366581.708905] NVRM: No NVIDIA graphics adapter found!

[5366581.709018] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 237

[5367065.591943] nvidia-nvlink: Nvlink Core is being initialized, major

device number 240

[5367065.593466] NVRM: No NVIDIA graphics adapter found!

[5367065.593658] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 240

[5383171.206304] nvidia-nvlink: Nvlink Core is being initialized, major

device number 240

[5383171.207798] NVRM: No NVIDIA graphics adapter found!

[5383171.207937] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 240

[5383747.500536] nvidia-nvlink: Nvlink Core is being initialized, major

device number 240

[5383747.501989] NVRM: No NVIDIA graphics adapter found!

[5383747.502191] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 240

[5392299.596901] nvidia-nvlink: Nvlink Core is being initialized, major

device number 240

[5392299.598190] NVRM: No NVIDIA graphics adapter found!

[5392299.598309] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 240

[5393057.598956] nvidia-nvlink: Nvlink Core is being initialized, major

device number 240

[5393057.600318] NVRM: No NVIDIA graphics adapter found!

[5393057.600446] nvidia-nvlink: Unregistered the Nvlink Core, major device

number 240

The driver installation is unable to locate the kernel source. Please make sure that the kernel source packages are installed and set up correctly.
If you know that the kernel source packages are installed and set up correctly, you may pass the location of the kernel source with the '--kernel-source-path' flag.

===========
= Summary =
===========

Driver:   Installation Failed
Toolkit:  Installation skipped
Samples:  Installation skipped

**Comment by nadegeguiglielmoni** [comment]
Hello,

What GPU do you have?
What do you get when you type `nvidia-smi` ?

**Comment by longzhangnation** [comment]
Hi @nadegeguiglielmoni ,
  it prints "no such an order " when I type `nvidia-smi`.

**Comment by nadegeguiglielmoni** [comment]
Then it means that you have not installed the NVIDIA driver. You can run:
`sudo apt install nvidia-driver-410`
If you have a recent GPU, it should be a proper driver. When the driver is properly installed, you should get an output from `nvidia-smi`.
Then you can try to install again cuda, but then when it asks whether you want to install the NVIDIA driver answer no, as you will have installed it already.

**Comment by longzhangnation** [comment]
but when i ran `sudo apt install nvidia-driver-410` ,it tol me that `E: cannot locate software package nvidia-driver-410` , Do you know how to deal with it ?

**Comment by nadegeguiglielmoni** [comment]
If you type `apt search nvidia-driver` you will see the drivers available.

**Comment by longzhangnation** [comment]
sorry it did not help , because some softwares will not be installed including "xserver-xorg-video-nvidia-410" "libnvidia-cfg1-410" . can you give me advice ?

**Comment by nadegeguiglielmoni** [comment]
It is difficult to help you without more information about the error. I think you should just google your error message, that's what I would do.

**Comment by cmdoret** [comment]
This issue is not related to instagraal but to graphics drivers installation. There are plenty of forums and websites dedicated to this kind of support (such as stackexchange). I suggest you ask this question there. If you have a instagraal-specific question though, we are happy to help !

**Comment by longzhangnation** [comment]
OK . Thank you for your help . I am looking for  how to install the graphics drivers .

**Comment by longzhangnation** [comment]
ok ,if i successfully install the graphics drivers , do i need to restart my server?

**Comment by nadegeguiglielmoni** [comment]
Yes

**Comment by longzhangnation** [comment]
Thank you.
