### ISSUE TITLE
issues when installing instagrall

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#11]
Hi,
  I tried another server with GPU , when I type  `nvidia-smi` ,it shows 
-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:B4:00.0 Off |                    0 |
| N/A   33C    P0    38W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

and  I try to install on it . During my installation , the performance of the server is "6 CPU / 1 GPU / 60.000GB (single node)" . I did what you wrote on the github, and finally it seems right.
  But when I type "`instagraal -h` ", it threw "`Segmentation fault (core dumped)`" . However, it works fine when I typed "`instagraal-polish -h`" . I guess it is because of out of memory ? do you have any idea to deal with ?
  Here is the core file when it dumped . Maybe you can see the problem from the log file .
[core.96317.gz](https://github.com/koszullab/instaGRAAL/files/4593123/core.96317.gz)

**Comment by longzhangnation** [comment]
Hi,
  I tried to increase the memory ,` 12 CPU / 2 GPU / 120.000GB` . but it still throws `Segmentation fault (core dumped)` . 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   28C    P0    37W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   29C    P0    35W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
This is the configuration. and here is the core file . 
[core.158244.gz](https://github.com/koszullab/instaGRAAL/files/4597134/core.158244.gz)

**Comment by nadegeguiglielmoni** [comment]
Hello, 

I cannot manage to look at your core file. 

There is no reason for instagraal to be out of memory with 60 GB, especially if it is just to look at the help. Do you have any information other than the Segmentation fault? Do you have anything preceeding this error?

**Comment by longzhangnation** [comment]
Hello,
  I'm sorry to forget you don't have the same server as me . When I read the content from the core file with gdb , it says "
#0  0x00002b08ce4132a9 in ?? ()
#1  0x0000000000000000 in ?? ()"
  I don't know what it means because I haven't learned so deep about linux. When I type` instagrall -h ,` it just throws "`Segmentation fault (core dumped)`" ,and no any other indications.

**Comment by nadegeguiglielmoni** [comment]
And is python3 working properly otherwise? If you have other programs that use python3 (like hicstuff for example), do you get the help normally?

**Comment by longzhangnation** [comment]
In fact , it is a new server I opened it yesterday . and I only use it for setting up instagraal . So you suspect maybe other programs the use python3 caused the error ？

**Comment by longzhangnation** [comment]
is instagraal used for virtual machine ? not for linux server ？

**Comment by nadegeguiglielmoni** [comment]
Well I can't really see why you would get a segmentation fault just for running the help, so I was wondering if you get this kind of problem with other programs.
We haven't tested it on virtual machines or servers, we have it installed on laptops and desktops, as it requires a GPU but not necessarily a lot of RAM.

**Comment by longzhangnation** [comment]
Well ,  it is reasonable to run the software on my server after its running on laptops . I also could not tell where it may be wrong . You could try to install the software on a linux server if possible . So that the application ranger of the software will be difined . At present, we all don't know whether it will work on the server . 
before , you ask me to type nvidia-smi , so what's the command used for ?

**Comment by nadegeguiglielmoni** [comment]
To install it on a Linux server, it requires an access to a server with GPU.

I use nvidia-smi to check whether the NVIDIA driver is properly installed.

**Comment by longzhangnation** [comment]
emmm , yes . You have to ensure your server GPU equipped . That's why I did not succeed in install instagraal on my own server and I changed another with GPU . But it tells  segment fault .  I don't have a laptop server with me , what a pity .

**Comment by longzhangnation** [comment]
Hello,
  I finally make it work now . I don't know how I manage it because what I do has been tested yesterday . now everything seems just right. So this proves the software will work fine on a server with GPU . Thank you for your patience @nadegeguiglielmoni  .

**Comment by longzhangnation** [comment]
By the way , I haven't test the software with my data because the hicstuff haven't finished. I type instagraal -h , and it shows the help interface . So I think it will pass if I use the read data.
