### ISSUE TITLE
Error: freeglut (/usr/local/bin/instagraal): failed to open display ''

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#12]
Hi,
  Sorry to interrupt you again . I successfully install the software , but meet some questions .  It throws "freeglut (/usr/local/bin/instagraal): failed to open display ''  "when I type `instagraal hic_data mer_20t_scf.fasta HIc_scaff`  . So I did that `export DISPLAY=:0` . Then  when I try again the scaffolding , it goes wrong saying "freeglut (/usr/local/bin/instagraal): failed to open display ':0' " .As you say on the github , we have to ensure X on the server , when I type "`top` ", it shows Xvfb is running on server . By the way , no graphics on the remote client . My server is  a linux server only with CPUs and GPUs on . So I can't control it with the movie running on it . Do you have any idea to cope with ? I don't know how to deal with , really . 
   If I have different servers with varying configurations . Will the more CPUs and GPUs will shorten the time of scaffolding ? Do you have any comparison between different servers of computers ?This may give me some clue for determining which one server to use.  And will the software fully use the RAM or anything concerning computing ? for that I noticed that you didnot provide any parameters for thread like that .

**Comment by nadegeguiglielmoni** [comment]
Hello,

To avoid the display issue, you should try to install this fork https://github.com/nowanda92/instaGRAAL . 
You may encounter an issue where it will indicate that the kernels are missing in a specific directory; you will need to copy manually the kernels (the files *.cu) from the instagraal/kernels folder to the directory where they are missing. 
instaGRAAL uses only 1 CPU, its speed is mainly based on your GPU. I believe I saw that your server provides a Tesla V100, I don't think you can get any better than that right now. In terms of RAM, the usage is minimal for genomes of some hundreds of Mb (only a few GB); I think the worst I've seen was about 30 GB for human.

**Comment by longzhangnation** [comment]
```
git clone https://github.com/nowanda92/instaGRAAL
cd instaGRAAL
python3 setup.py install
```
 it shows 

> - /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
>   warnings.warn(msg)
> /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
>   warnings.warn(msg)
> running install
> Checking .pth file support in /usr/local/lib/python3.6/dist-packages/
> /usr/bin/python3 -E -c pass

> TEST PASSED: /usr/local/lib/python3.6/dist-packages/ appears to support .pth files
> running bdist_egg
> running egg_info
> writing instagraal.egg-info/PKG-INFO
> writing dependency_links to instagraal.egg-info/dependency_links.txt
> writing entry points to instagraal.egg-info/entry_points.txt
> writing requirements to instagraal.egg-info/requires.txt
> writing top-level names to instagraal.egg-info/top_level.txt
> reading manifest file 'instagraal.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'kernels/*'
> writing manifest file 'instagraal.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build/lib
> creating build/lib/instagraal
> copying instagraal/fragment.py -> build/lib/instagraal
> copying instagraal/vector.py -> build/lib/instagraal
> copying instagraal/cuda_lib_gl_single.py -> build/lib/instagraal
> copying instagraal/log.py -> build/lib/instagraal
> copying instagraal/instagraal.py -> build/lib/instagraal
> copying instagraal/optim_rippe_curve_update.py -> build/lib/instagraal
> copying instagraal/simu_single.py -> build/lib/instagraal
> copying instagraal/parse_info_frags.py -> build/lib/instagraal
> copying instagraal/pyramid_sparse.py -> build/lib/instagraal
> copying instagraal/init_nuisance.py -> build/lib/instagraal
> copying instagraal/__init__.py -> build/lib/instagraal
> copying instagraal/gpustruct.py -> build/lib/instagraal
> copying instagraal/version.py -> build/lib/instagraal
> copying instagraal/glutil.py -> build/lib/instagraal
> copying instagraal/leastsqbound.py -> build/lib/instagraal
> copying instagraal/linkage.py -> build/lib/instagraal
> Traceback (most recent call last):
>   File "setup.py", line 72, in <module>
>     "instagraal-polish=instagraal.parse_info_frags:main",
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install.py", line 67, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install.py", line 109, in do_egg_install
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/bdist_egg.py", line 161, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/bdist_egg.py", line 147, in call_command
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install_lib.py", line 10, in run
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 107, in build
>     self.run_command('build_py')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 52, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 107, in build_package_data
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 65, in __getattr__
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 79, in _get_data_files
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 98, in find_data_files
> TypeError: can only concatenate list (not "str") to list

```
cd instagraal
cp -r kernels/ ../
cd ../
python3 setup.py install
```

> /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
>   warnings.warn(msg)
> /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
>   warnings.warn(msg)

> running install
> Checking .pth file support in /usr/local/lib/python3.6/dist-packages/
> /usr/bin/python3 -E -c pass
> TEST PASSED: /usr/local/lib/python3.6/dist-packages/ appears to support .pth files
> running bdist_egg
> running egg_info
> writing instagraal.egg-info/PKG-INFO
> writing dependency_links to instagraal.egg-info/dependency_links.txt
> writing entry points to instagraal.egg-info/entry_points.txt
> writing requirements to instagraal.egg-info/requires.txt
> writing top-level names to instagraal.egg-info/top_level.txt
> reading manifest file 'instagraal.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'instagraal.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg

> running install_lib
> running build_py
> copying instagraal/version.py -> build/lib/instagraal
> Traceback (most recent call last):
>   File "setup.py", line 72, in <module>
>     "instagraal-polish=instagraal.parse_info_frags:main",
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install.py", line 67, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install.py", line 109, in do_egg_install
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)

 

>  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/bdist_egg.py", line 161, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/bdist_egg.py", line 147, in call_command
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/install_lib.py", line 10, in run
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 107, in build
>     self.run_command('build_py')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 52, in run
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 107, in build_package_data
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 65, in __getattr__
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 79, in _get_data_files
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
>   File "/usr/local/lib/python3.6/dist-packages/setuptools-19.6-py3.6.egg/setuptools/command/build_py.py", line 98, in find_data_files
> TypeError: can only concatenate list (not "str") to list

So , what did I do wrong ?

**Comment by longzhangnation** [comment]
Sorry , after I upgrade my setuptools , it did not show the typeerror . Now I am trying to solve the kernels/*.cu file . I did not find good way to move it .

**Comment by longzhangnation** [comment]
So when I type `python3 setup.py install ` ,it shows that 

> error in instagraal setup command: "values of 'package_data' dict" must be a list of strings (got 'kernels/*.cu')
 Where should I move the *.cu files to ? can you give me any clue ?

**Comment by nadegeguiglielmoni** [comment]
Hi,

Sorry for not answering earlier. It's good that you figured it out cause I had no idea how to fix this.

In setup.py, could you replace line 63 where you have: 
`package_data={"instagraal": ("kernels/*.cu")},`
by
`package_data={"instagraal": ["kernels/*.cu"]},`

**Comment by longzhangnation** [comment]
Sorry, it is so hard to run the software successfully , and I have tried to install the software for half a month , and it is just much hard to install . Because I don't have much time to install it ,so I have to quit the installation . Hope you will developed a easier-to-install version . Will you ? For example I can run it on CPU , like 3D-DNA ?

**Comment by nadegeguiglielmoni** [comment]
Hello,

I am sorry to read this. Have you tried what I had suggested though? Just to know if it can help or not...

The advantage of having instaGRAAL run on GPU instead of CPU is that GPUs run parallel jobs much faster than CPUs. This way you can run instaGRAAL on a desktop or even a laptop as long as they have an NVIDIA GPU, which is quite convenient when you have limited access to clusters. I must emphasize that you do not need the latest shiniest GPU for instaGRAAL like a Tesla V100, your typical gamer GPU is plenty enough (even my GTX960M on my laptop can handle it).

**Comment by longzhangnation** [comment]
Thanks for you patience . And I did what you suggest above , but it shows something else. When I use the command `instagraal ./hic_data assemble.fasta ./Hic_scafflding` , it throws that :

> INFO :: Selected_device: Tesla V100-SXM2-16GB
> Traceback (most recent call last):
>   File "/usr/local/bin/instagraal", line 9, in <module>
>     load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 2164, in main
>     output_folder=output_folder,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 208, in __init__
>     self.cuda_gl_init()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 1448, in cuda_gl_init
>     curr_gpu, flags=cudagl.graphics_map_flags.NONE
> pycuda._driver.Error: cuGLCtxCreate failed: unknown error

it seem that the pycuda driver is not  wrong . But I don't know how to fix it .

**Comment by longzhangnation** [comment]
it seems the question has been put  up by others [https://github.com/koszullab/instaGRAAL/issues/3#issue-449843579](url), have you gotten to know how to fix ?

**Comment by nadegeguiglielmoni** [comment]
This step concerns interoperability with OpenGL. Have you properly installed pyopengl for Python3? And when you installed pycuda, did you use the option --cuda-enable-gl ? Could you send me what is inside the file siteconf.py in the pycuda folder?

**Comment by longzhangnation** [comment]
yes , the pyopengl is installed and the option --cuda-enable-gl also used .Here is the sitecon.py

>

>  BOOST_INC_DIR = []
> BOOST_LIB_DIR = []
> BOOST_COMPILER = 'gcc43'
> USE_SHIPPED_BOOST = False
> BOOST_PYTHON_LIBNAME = ['boost_python-py36']
> BOOST_THREAD_LIBNAME = ['boost_thread']
> CUDA_TRACE = False
> CUDA_ROOT = '/app/common/cuda/10.0'
> CUDA_ENABLE_GL = True
> CUDA_ENABLE_CURAND = True
> CUDADRV_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
> CUDADRV_LIBNAME = ['cuda']
> CUDART_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
> CUDART_LIBNAME = ['cudart']
> CURAND_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib64/stubs']
> CURAND_LIBNAME = ['curand']
> CXXFLAGS = []
> LDFLAGS = []

**Comment by nadegeguiglielmoni** [comment]
So everything is fine on that part.

I have found a similar issue but sadly... unresolved. One thing that you could try would be to replace in instagraal.py line 1443 that contains 
`if bool(OpenGL.GLUT.glutMainLoopEvent):`
by 
`if False:`

**Comment by longzhangnation** [comment]
I use the same code ,and run again ,another error throws, say:

> Traceback (most recent call last):
>   File "/usr/local/bin/instagraal", line 9, in <module>
>     load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 2164, in main
>     output_folder=output_folder,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 208, in __init__
>     self.cuda_gl_init()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 1451, in cuda_gl_init
>     import pycuda.gl.autoinit
>   File "/usr/local/lib/python3.6/dist-packages/pycuda-2019.1.2-py3.6-linux-x86_64.egg/pycuda/gl/autoinit.py", line 9, in <module>
>     context = make_default_context(lambda dev: cudagl.make_context(dev))
>   File "/usr/local/lib/python3.6/dist-packages/pycuda-2019.1.2-py3.6-linux-x86_64.egg/pycuda/tools.py", line 205, in make_default_context
>     "on any of the %d detected devices" % ndevices)
> RuntimeError: make_default_context() wasn't able to create a context on any of the 1 detected devices
>

**Comment by nadegeguiglielmoni** [comment]
Hmm it's basically the same error. Can you try adding after line 1442:
`cuda.Context.pop()`
?

**Comment by longzhangnation** [comment]
with the line 1443` if False :` ?

**Comment by nadegeguiglielmoni** [comment]
Yes

**Comment by longzhangnation** [comment]
> Traceback (most recent call last):
>   File "/usr/local/bin/instagraal", line 9, in <module>
>     load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 2165, in main
>     output_folder=output_folder,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 208, in __init__
>     self.cuda_gl_init()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 1443, in cuda_gl_init
>     cuda.Context.pop()
> pycuda._driver.LogicError: context::pop failed: invalid device context - cannot pop non-current context
> 
>

**Comment by longzhangnation** [comment]
So ,any idea?

**Comment by nadegeguiglielmoni** [comment]
As the problem comes from pycuda, I followed on an issue posted on the pycuda github https://github.com/inducer/pycuda/issues/212 . If you could participate to this issue, it would be very helpful.

**Comment by longzhangnation** [comment]
OK, I will go to see and try .

**Comment by longzhangnation** [comment]
THank you

**Comment by nadegeguiglielmoni** [comment]
I realize I may have given you a wrong indication, could you try this version https://github.com/koszullab/instaGRAAL/tree/master#external-libraries instead of the one I told you before?

**Comment by longzhangnation** [comment]
Hmm,OK . I will try that , It doesn't matter. Thank you .

**Comment by longzhangnation** [comment]
should I install the the no_opengl branch version  instagrall ? . Because I read a new question , which describes a situation like me ，and was solved .

**Comment by nadegeguiglielmoni** [comment]
Yes indeed.

**Comment by longzhangnation** [comment]
I noticed that you give the address is different from that in #13 ,so both are fine for me ?

**Comment by nadegeguiglielmoni** [comment]
Go for this one https://github.com/koszullab/instaGRAAL/tree/no_opengl

**Comment by longzhangnation** [comment]
Thank you . I am trying .

**Comment by longzhangnation** [comment]
it seems works fine for the time being . I test my data , and it runs like in the #13 . Thank you . I will open another issue if I met other problem . Thank you again . Have a nice day !
