### ISSUE TITLE
keyerror :"Unable to open object (object '0' doesn't exist)"

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#14]
when use my data to test the instagraal , it looks fine at first . later , it stopped , throwing error,

> INFO :: start filtering
> WARNING :: /usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/pyramid_sparse.py:103: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
>   pyramid_0 = h5py.File(init_pyramid_file)
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/instagraal", line 11, in <module>
>     load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 1178, in main
>     output_folder=output_folder,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/instagraal.py", line 160, in __init__
>     output_folder=output_folder,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/simu_single.py", line 74, in __init__
>     self.select_data_set(name)
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/simu_single.py", line 743, in select_data_set
>     thresh_factor=self.thresh_factor,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/pyramid_sparse.py", line 113, in build_and_filter
>     thresh_factor=thresh_factor,
>   File "/usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/pyramid_sparse.py", line 833, in remove_problematic_fragments
>     level = pyramid["0"]
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object '0' doesn't exist)"

**Comment by longzhangnation** [comment]
sorry , I put some file into the hic data folder . so others do not make the same mistake like me . 
By the way ,will the software take large room when running ? because I don't have enough room for this server .

**Comment by nadegeguiglielmoni** [comment]
The pyramids folder may take some tens of GB for big genomes, and you can delete it when the run is over. If your genome is over 1 Gb, I would recommend using parameter -l 5.
