### ISSUE TITLE
should I worry about the warning?

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#15]
Hi,
  I ran the software successfully . I use my date ,generated by the command `hicstuff pipeline  --enzyme MboI --iterative -g mer_20t_scf.fasta  -o ./ -t 35 hic_1_clean.fastq.gz hic_2_clean.fastq.gz` ,to scaffold my genome .
> INFO :: p from estimate parameters  = [0.609231115267729, 62.68078982754462, -1.1638487993936344, 2, 54875.35389675029]
> INFO :: mean value trans = 0.04067848007063246
> INFO :: BEWARE!!! : I will lower mean value trans  !!!
> INFO :: estimate max dist cis trans = 27023.030339687124
> INFO :: cycle = 0
> INFO :: generate new fasta file...
> INFO :: cycle = 1
> INFO :: generate new fasta file...
> INFO :: cycle = 2
> INFO :: generate new fasta file...
> INFO :: cycle = 3
> INFO :: generate new fasta file...
> INFO :: cycle = 4
> WARNING :: /usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/cuda_lib_gl_single.py:1868: RuntimeWarning: invalid value encountered in less
>   filtered_score[filtered_score < 0] = 0
> 
> INFO :: generate new fasta file...
> INFO :: cycle = 5
> WARNING :: /usr/local/lib/python3.6/dist-packages/instagraal-0.1.6-py3.6.egg/instagraal/cuda_lib_gl_single.py:3626: RuntimeWarning: overflow encountered in exp
>   ratio = np.exp((self.likelihood_nuis - self.likelihood_t) / F_t)

I don't know whether I should worry about the warning like "lower mean value " and other warning as you can see . 
In addition, how many cycles I should run to get a good result ? I use the default set , but you recommend in other issue 15 times will be OK . How can I asses the good result ? By genome metrics like N50 ,or something else ?
Thank you !

**Comment by longzhangnation** [comment]
In addition, it has run 14 cycles , and the quast  `-s` result is as follows,

> Assembly                    genome      genome_broken
> # contigs (>= 0 bp)         4771        -
> # contigs (>= 1000 bp)      3177        3385
> # contigs (>= 5000 bp)      929         1136
> # contigs (>= 10000 bp)     561         766
> # contigs (>= 25000 bp)     338         537
> # contigs (>= 50000 bp)     152         338
> Total length (>= 0 bp)      1034150433  -
> Total length (>= 1000 bp)   1033267630  1033246671
> Total length (>= 5000 bp)   1027699361  1027677277
> Total length (>= 10000 bp)  1025176720  1025138238
> Total length (>= 25000 bp)  1021827583  1021670148
> Total length (>= 50000 bp)  1014710265  1014100210
> # contigs                   4155        4363
> Largest contig              794255068   57383890
> Total length                1033981137  1033960178
> GC (%)                      41.25       41.25
> N50                         794255068   18245066
> N75                         794255068   8933355
> L50                         1           18
> L75                         1           38
> # N's per 100 kbp           2.02        0.00

So will the result be changed later in the "`genome`" column ?

**Comment by longzhangnation** [comment]
I run a second time for the data ,generated by `hicstuff pipeline  --enzyme MboI --aligner minimap2   -g  mer_20t_scf.fasta    -o ./ -f  -t 55  hic_R1_clean.fastq.gz  hic_R2_clean.fastq.gz` , the hicstuff log is like this ,

> INFO :: Genome digested into 1706505 fragments with a median length of 370.0
> INFO :: 66% reads (single ends) mapped with Q >= 30 (542992233/816928950)
> INFO :: Filtering with thresholds: uncuts=5 loops=2
> INFO :: Proportion of inter contacts: 62.66% (intra: 28144941, inter: 47224947)
> INFO :: 138524199 pairs discarded: Loops: 3979518, Uncuts: 134195576, Weirds: 349105
> INFO :: 75369888 pairs kept (35.24%)
> INFO :: 75369886 pairs used to build a contact map of 1706505 bins with 24999650 nonzero entries.
> INFO :: Contact map generated after 4h 36m 40s

and the optput for the cycle1 is as follows,

> Assembly                    genome      genome_broken
>  contigs (>= 0 bp)         4083        -
>  contigs (>= 1000 bp)      2793        3001
>  contigs (>= 5000 bp)      909         1117
>  contigs (>= 10000 bp)     569         775
>  contigs (>= 25000 bp)     348         551
>  contigs (>= 50000 bp)     166         353
> Total length (>= 0 bp)      1034149374  -
> Total length (>= 1000 bp)   1033443288  1033422329
> Total length (>= 5000 bp)   1028681056  1028660097
> Total length (>= 10000 bp)  1026385158  1026351839
> Total length (>= 25000 bp)  1022965180  1022878283
> Total length (>= 50000 bp)  1015974904  1015312555
>  contigs                   3558        3766
> Largest contig              479109233   53796793
> Total length                1034003933  1033982974
> GC (%)                      41.25       41.25
> N50                         121367597   15707538
> N75                         108085223   8497465
> L50                         2           19
> L75                         4           42
>  N's per 100 kbp           2.02        0.00

what's more , it is expected to generate 50 largest scaffolds for my genome because its chromosome is 50 . So it may merge some chromosomes during scaffolding although the assembly is quite long . Do you have any idea to deal with the problem ?

**Comment by longzhangnation** [comment]
the last line, it shows only a title ,no sequence after it ,like this,

> $tail genome.fasta
> GATCTCGGGGGTGACGTACAAAATCCAGCGTGGACGCCGTCGCCCTTCCATT
> >3C-assembly-contig_4761
> GATCTCCATTCTTGGAGACTTCAATGTTCACCACTAGCTTTCCTCTCCCCCC
> >3C-assembly-contig_4277
> GATCATTTTTTGGGCTTGTTTCTGTTGTTCTATGTTGGACTTCATTTGTTC
> >3C-assembly-contig_1777
> GATCCAAATTATTCCAGCAAAGCAAATCACCAAGAATTCTGCACATTAGT
> >3C-assembly-contig_4150
> TCGGTATCTATGAAGGTGAATAACAAAAAAACAAACAGTGTTTTTTGATC
> >3C-assembly-contig_356
> 

Is it normal ?

**Comment by nadegeguiglielmoni** [comment]
Hello, 

The number of cycles depends on whether the structure has converged or not. Unless you are in a rush, I would recommend running at least 50 cycles. I also would recommend to not check the genome.fasta file before at least 10 cycles, because the genome is modified a lot in the first cycles.
 
For the first run you mention, which parameters did you use when running hicstuff ? I would recommend using the parameters recommended here https://github.com/koszullab/instaGRAAL/issues/9 : 
- do not use --filter
- use --iterative (to improve recovery of chimeric reads, which may contain the ligation site in R1 or R2)
- use bowtie2 (default) or bwa for mapping, as minimap2 is fast but less adequate for short reads

Is your assembly generated with long-reads only? if you have shotgun short reads, have you evaluated the k-mer completeness of your contigs prior to scaffolding? I personnally love KAT https://kat.readthedocs.io/en/latest/walkthrough.html and I systematically use `kat comp` to check whether the contigs are good and you do not have uncollapsed haplotypes. 

I don't think that it is abnormal to have an empty sequence, you may have looked at genome.fasta while it was being written.

**Comment by longzhangnation** [comment]
` hicstuff pipeline --enzyme MboI --iterative -g mer_20t_scf.fasta -o ./ -t 35 hic_1_clean.fastq.gz hic_2_clean.fastq.gz` this the command I use for the first run,and I use instagraal with the default parameters ,too  . For result of  the first run after cycle 15 , the N50 did not change so much . According to your paper on the  biorxiv   , I think the assembly result will vary for first several cycles. But I did not see it for my data . I think -bomb for the instagraal will fit my data and I am trying it . I assembly my genome with long reads only .

**Comment by nadegeguiglielmoni** [comment]
You should try using the parameter `-c 0` for instagraal.

**Comment by longzhangnation** [comment]
May I ask about the meaning of  `-b` ?  In my opinion , it will break the genome or bin the genome before scaffolding my genome ? Am I right ? Why shouldn't I filter during the hicsutff ? because the chemiric reads may affect my scaffolding , or the instagraal will deal with the noise?

**Comment by nadegeguiglielmoni** [comment]
--bomb is supposed to break the genome, but you shouldn't need it if your contigs are good. Filtering prior to scaffolding is unnecessary as it eliminates spurious events that are not a problem for scaffolding. The chimeric reads are the "good" ones, as they are the result of a ligation event between two fragments of DNA and therefore provide contact information. 

If your genome was assembled with long reads only, you may have a number of errors in your assembly that can lead to erroneous Hi-C reads mapping. If you used Nanopore reads only, then even with a high coverage you will have remaining errors, and Illumina reads are the way to go to polish your assembly. If you have PacBio reads, with a high enough coverage the errors are compensated. You can then use a polisher adapted for long reads such as Racon.

**Comment by longzhangnation** [comment]
By the way , what will it happen when I tune up or the the `-c` ? I don't quite understand the parameter .  I have used the long reads to correct the assembly once and short read thrice .

**Comment by nadegeguiglielmoni** [comment]
Ah so errors should not be the problem. Then I'd say to try different parameters, like -l 4 -c 0, -l 5 -c 1...
The -c parameter is the value of standard deviation below the mean coverage for which restriction fragments are filtered, so if you set it to 0 it's basically disabled.

**Comment by longzhangnation** [comment]
OK, I will try again . Thank you for your generous help . Maybe the parameter is fine or not . Hope it will . The scaffolding result is very long , but what a pity , the result is not expected . Thanks again

**Comment by longzhangnation** [comment]
Eh , from my experience , running one cycle will take me around 5 hours , and the software could not support multi thread , so I will spend long time for waiting for the result . And its output is  not as satisfying as 3D-DNA . Maybe you have test some other species , does it outperform the 3D_DNA, too ? T From your view , will the first cycles output L50 equal 2 or 3 even 1 ? I think it is abnormal ,maybe caused by my data . But it did not leave much time to explore . By the way , different parameters setting did not change much at first cycles , and the N50 is quite long so that I have to doubt the result .
