### ISSUE TITLE
freeglut problem

### ISSUE THREAD

**Issue by KseniaJuravel** [koszullab/instaGRAAL#16]
Hello,
I get the following error:
freeglut (PATH to instagraal bin)
ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
Is there a way to get rid of it?

Thank you

**Comment by nadegeguiglielmoni** [comment]
Hello,

Installing the no_opengl branch should fix it:

`git clone --single-branch --branch no_opengl https://github.com/koszullab/instaGRAAL.git`

**Comment by KseniaJuravel** [comment]
Hi, 
Thank you for the help provided. It solved the display problem but new error arises:

1 error detected in the compilation of "/tmp/tmpxft_00007171_00000000-6_kernel.cpp1.ii".
]
Any ideas on that?

**Comment by cmdoret** [comment]
Sorry, we have never envountered this error, perhaps it may have something to do with your environment.
I will be closing this, but if you have since found the source feel free to reopen.
