### ISSUE TITLE
Reference Dictionary issues

### ISSUE THREAD

**Issue by MaxSchmidt1** [koszullab/instaGRAAL#19]
Hello,
I have been working myself through installing instagraal on Fedora 33 and after several issues with cuda, pycuda and h5py I finally got to a stage where I can generate the pyramid files but now I get a new error that seems to be related to the sequence names in my input reference not being properly loaded into a python dictionary. 
I am using a 760 Mb Genome assembled with NECAT and filtered with purge_duplicats. The contigs are named bctg00000000 up to bctg00001099 (not all numbers in between are used).
I did install instagraal via
`sudo pip3 install -e git+https://github.com/koszullab/instagraal.git@master#egg=instagraal`

When I run instagraal it seems to work fine till the stage where it is loading the reference. Then I get the following error

```
INFO :: pyramid loaded
INFO :: loading data from level = 4
INFO :: import reference genome
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 33, in <module>
    sys.exit(load_entry_point('instagraal', 'console_scripts', 'instagraal')())
  File "/mnt/data/max/20201213_Vinca_instagraal/src/instagraal/instagraal/instagraal.py", line 2149, in main
    p2 = window(
  File "/mnt/data/max/20201213_Vinca_instagraal/src/instagraal/instagraal/instagraal.py", line 212, in __init__
    self.simulation = simulation(
  File "/mnt/data/max/20201213_Vinca_instagraal/src/instagraal/instagraal/simu_single.py", line 108, in __init__
    self.level.build_seq_per_bin(genome_fasta=self.fasta)
  File "/mnt/data/max/20201213_Vinca_instagraal/src/instagraal/instagraal/pyramid_sparse.py", line 2215, in build_seq_per_bin
    seq_frag = self.pyramid.dict_sequence_contigs[init_contig][
KeyError: 'bctg00000000'
```
Can you tell me what I am missing and how it could be fixed?

Thanks

**Comment by nadegeguiglielmoni** [comment]
Hello,

How did you run hicstuff?

How are the names written in your fasta file, and how does the head of the file fragments_list.txt look like?

**Comment by MaxSchmidt1** [comment]
Hello,
I ran hicstuff with pretty much the default settings using minimap2 as the aligner.
`hicstuff pipeline -t 32 -a minimap2 -e DpnII -o out/ -g curated-a85.fasta VmiMa-Hi-C-MS01-N1_1.fq.gz VmiMa-Hi-C-MS01-N1_2.fq.gz`

The contigs in the fasta reference look like this (`grep "^>" curated-a85.fasta | head`)
```
>bctg00000000 
>bctg00000001 
>bctg00000002 
>bctg00000003 
>bctg00000004 
>bctg00000005 
>bctg00000006 
>bctg00000007 
>bctg00000008 
>bctg00000009 
```
The head of fragments_list.txt looks like this
```
id	chrom	start_pos	end_pos	size	gc_content
1	bctg00000000	0	130	130	0.36153846153846153
2	bctg00000000	130	1435	1305	0.3241379310344828
3	bctg00000000	1435	1550	115	0.24347826086956523
4	bctg00000000	1550	2035	485	0.2804123711340206
5	bctg00000000	2035	2224	189	0.4021164021164021
6	bctg00000000	2224	2987	763	0.31716906946264745
7	bctg00000000	2987	3161	174	0.3218390804597701
8	bctg00000000	3161	3221	60	0.31666666666666665
9	bctg00000000	3221	3328	107	0.3644859813084112
```

**Comment by nadegeguiglielmoni** [comment]
And what did you get in the hicstuff log?

**Comment by MaxSchmidt1** [comment]
```
## hicstuff: v2.3.2 log file
## date: 2020-12-31 10:03:07
## enzyme: DpnII
## input1: VmiMa-Hi-C-MS01-N1_1.fq.gz 
## input2: VmiMa-Hi-C-MS01-N1_2.fq.gz
## ref: curated-a85.fasta
---
2020-12-31,10:52:50 :: INFO :: Genome digested into 2402906 fragments with a median length of 193.0
2020-12-31,11:08:21 :: INFO :: 37% reads (single ends) mapped with Q >= 30 (162652283/438456590)
2020-12-31,12:11:50 :: INFO :: 45259742 pairs used to build a contact map of 2402906 bins with 6495293 nonzero entries.
2020-12-31,12:11:54 :: INFO :: Contact map generated after 2h 8m 46s
```

**Comment by nadegeguiglielmoni** [comment]
Seems weird that it would not find it when it's there. I would also check the sparse matrix, perhaps it did not find any contact for the first contig and that's why it's not there...

The first thing that I would recommend is to try mapping again with the hicstuff pipeline, but with bowtie2 or bwa as aligner. minimap2 is not optimal for reads below 100 bp, and when reads are longer than 100 bp you should really use --iterative as you may have many reads with the ligation site that would not map.

**Comment by MaxSchmidt1** [comment]
I did try and use bowtie2 as the mapper instead of minimap but the error stayed the same. I also removed the first contig from the reference and rerun HiCstuff and instaGRAAL but then I just get the same error for the next contig. 
I also tried using the --iterative flag but again it fails at the same stage.
Do you have another idea what I could try?

**Comment by nadegeguiglielmoni** [comment]
Just to be sure, what is the command line you run for instaGRAAL?

**Comment by MaxSchmidt1** [comment]
`instagraal out4 curated-a85_3.fasta`

whereas `out4` is the output folder of hicstuff. There I used
`hicstuff pipeline -t 32 -a bowtie2 -e DpnII --iterative -o out4/ -g curated-a85_3.fasta VmiMa-Hi-C-MS01-N1_1.fq.gz VmiMa-Hi-C-MS01-N1_2.fq.gz` 

and `curated-a85_3.fasta` is my reference of which I had removed the first contig (before hicstuff)

**Comment by nadegeguiglielmoni** [comment]
What were the issues you had with h5py? It might be the culprit here too...

**Comment by MaxSchmidt1** [comment]
Pretty much the same as described in issue #17 
so I installed an older h5py version as described with `pip install h5py==2.10.0`
No I am just getting the usual Deprecation warning for that
`WARNING :: /mnt/data/max/20201213_Vinca_instagraal/src/instagraal/instagraal/pyramid_sparse.py:1532: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  self.data = h5py.File(self.pyramid_file)`

**Comment by cmdoret** [comment]
I just encountered the same error because reference contig IDs contained spaces in their names.
Like many programs, hicstuff removes spaces in contig IDs, so when you feed its output to instagraal along with the original fasta, contig IDs are different.
