### ISSUE TITLE
X Error of failed request: BadValue

### ISSUE THREAD

**Issue by psimion** [koszullab/instaGRAAL#2]
Trying to run instagraal (version 0.1.2) yielded the following issue:

```
genome="Avaga.Masurca_A1.fasta"
hicstuff_indir="Adineta_vaga.Masurca_A1.Hi-C_reads"
outdir="Adineta_vaga.Masurca_A1.Hi-C_reads_GRAAL"
instagraal $hicstuff_indir $genome $outdir
```
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  154 (GLX)
>   Minor opcode of failed request:  24 (X_GLXCreateNewContext)
>   Value in failed request:  0x0
>   Serial number of failed request:  37
>   Current serial number in output stream:  38

I do not know where to start with such an error output, so any help would be appreciated !
thanks,
paul

Another issue previously appeared, but I corrected it by installing "freeglut3-dev" : 
> OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```
sudo apt-get install freeglut3-dev
```

Of note:
```
ls $hicstuff_indir 
```
> abs_fragments_contacts_weighted.txt  fragments_list.txt  hicstuff_20190307174358.log  info_contigs.txt  plots
```
nvcc --version
```
> 	nvcc: NVIDIA (R) Cuda compiler driver
> 	Copyright (c) 2005-2019 NVIDIA Corporation
> 	Built on Fri_Feb__8_19:08:17_PST_2019
> 	Cuda compilation tools, release 10.1, V10.1.105
```
lspci | grep -i nvidia
```
> 	02:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
> 	02:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
```
uname -m && cat /etc/*release | head -n2
```
> 	x86_64
> 	DISTRIB_ID=Ubuntu
> 	DISTRIB_RELEASE=18.10

**Comment by nadegeguiglielmoni** [comment]
Hello, 

This error is caused when running instaGRAAL via ssh: it fails to open the display. The most recent version no longer has the GUI and works with ssh.
