### ISSUE TITLE
no opengl branch

### ISSUE THREAD

**Issue by MWSchmid** [koszullab/instaGRAAL#21]
Hi

After a few hiccups, I managed to get the no_opengl branch to work, this should work on Ubuntu 18.04 server:

```sh
sudo apt-get install ubuntu-drivers-common
sudo ubuntu-drivers devices
sudo apt-get install nvidia-driver-460 
# reboot
sudo apt-get install libglu1-mesa libxi-dev libxmu-dev libglu1-mesa-dev freeglut3-dev hdf5-tools libboost-all-dev
sudo apt-get install python3-numpy python3-scipy python3-matplotlib python3-h5py python3-opengl python3-docopt python3-biopython
sudo apt-get install nvidia-cuda-toolkit
sudo apt-get install gcc-8 g++-8

git clone --recurse-submodules https://github.com/inducer/pycuda.git
cd pycuda
python3 configure.py --cuda-enable-gl --no-use-shipped-boost
sudo python3 setup.py install

git clone --branch no_opengl https://github.com/koszullab/instagraal.git
cd instagraal
sudo python3 setup.py install
# reboot
```

So far it's running, but it looks like it will take a loooooooong time (I'm at "0.005421464662893327% proceeded", after 3 hours...). Is the version with opengl support much faster? I.e., is it worth to get it to run? 

Best regards

**Comment by nadegeguiglielmoni** [comment]
Hello,

The opengl branch is in fact slower than the no_opengl one (because of the graphical display). The speed is impacted by the size of the genome and the fragmentation. You can change the parameter --level to accelerate instaGRAAL (I personally use -l 5 for genomes > 1Gb).

**Comment by MWSchmid** [comment]
Ok, thanks for the hint, will try. The genome is around 700 Mb, around 200'000 scaffolds.

Btw, when you run the regular version, do you do that as well via SSH/screen, or always on a machine with a display?

**Comment by nadegeguiglielmoni** [comment]
The regular version usually results in errors when we try to run it without display, the no_opengl is more adequate. Some prefer with the display, so that is why we are keeping it for now. 

Your assembly has 200,000 fragments? That may indeed take some time... I just hope that you have a high enough Hi-C coverage, if not there may be a lot of uncovered/poorly covered fragments.

**Comment by MWSchmid** [comment]
Ok, thanks for the info.

Yes, it's quite a lot. I also have a version of it with less scaffolds but a few mis-assemblies from another HiC tool (would instagraal fix those?). I'm currently testing different HiC-assembly tools, that's why I also have some suboptimal draft assemblies :)

**Comment by nadegeguiglielmoni** [comment]
instaGRAAL may fix these misassemblies. With that many fragments, the runtime may be quite long (especially the first cycles). You can take a look at the intermediary assembly (called genome.fasta), but you should wait for a few cycles (over 10 cycles).
