### ISSUE TITLE
in requirements.txt, force install biopython 1.75, not latest version

### ISSUE THREAD

**Issue by scottgeib** [koszullab/instaGRAAL#22]
due to changes in Bio.Seq and IUPAC support in latest biopython, modify the requirements list to install biopython==1.75 and not update to latest. Otherwise i was get an error loading IUPAC running instagraal-polish with v 1.78 biopython.

**Comment by cmdoret** [comment]
Thanks, the biopython version in `requirements.txt` has been pinned in 7cc3daa
