### ISSUE TITLE
Should the initial reference assembly and final polished genome have equal sequence lengths?

### ISSUE THREAD

**Issue by JamieAlfieri** [koszullab/instaGRAAL#25]
I've run hicstuff, instagraal, and polish to obtain a scaffold assembly (code below). As expected, the final polished genome has better contiguity measures than the initial reference assembly, which was a long read assembly (Initial ref N90 = 0.71, N50 = 10.43; whereas the final polished genome N90 = 12.52, N50 = 24.83). 

However, I am surprised that the sequence length (174.19) and file size (177.1 MB) is equal between the initial reference assembly and final polished genome. This is especially surprising to me considering the assemblies have different contig counts (initial ref = 527 vs. final polished genome = 707). It is also interesting to note that the polishing step did not change our instagraal output assembly (genome.fasta) at all.

1) Is it "normal" behavior for the initial reference assembly to be the same length as the final polished genome?
2) Is it "normal" behavior for the polishing step to not improve the assembly at all?

`
hicstuff pipeline -t 60 -a minimap2 -e DpnII -o hicstuff_out/ -g initial.fa hic_reads_R1.fastq hic_reads_R2.fastq
`
`
instagraal hicstuff_out initial.fa instagraal_out/
`
`
instagraal-polish -m polishing -i info_frags.txt -f initial.fa -o final_polished_assembly.fa
`

**Comment by cmdoret** [comment]
Hi @JamieAlfieri,

yes it can happen that the polished assembly is identical to the instagraal assembly in case there are no Hi-C induced errors detected.
