### ISSUE TITLE
What does "--bomb" do?

### ISSUE THREAD

**Issue by shelkmike** [koszullab/instaGRAAL#27]
There is an option "--bomb" to "explode the genome prior to scaffolding". Could you please explain in more detail what it does?

**Comment by cmdoret** [comment]
Hi @shelkmike ,

`--bomb` will splits contig into restriction fragments and reassemble those fragments according to their contacts.
This is only useful if the original contigs are of poor quality but with modern (long reads) assemblies, it is likely to yield worse results.
