### ISSUE TITLE
Description of new_info_frags.txt file

### ISSUE THREAD

**Issue by Karimi-81** [koszullab/instaGRAAL#28]
Hi there,
Thank you for developing the instaGRAAL and your support. I have polished my genome assembly using instagraal-polish. I am a bit confused about understanding the meaning of -1 in the new_info_frags.txt file. Particularly, there is a contig (scaffold) that was aligned to mitochondrial DNA (I guess it is a mitochondrial genome) but the length of this contig is 32 kb while we expect the size of 16 kb for mitochondrial genome:
>3C-assembly|contig_80
init_contig	id_frag	orientation	start	end
ptg000178l	22986	1	0	16509
ptg000178l	-1	1	16509	32593

I wonder if you can provide more details about the structure of info_frags.txt. You mentioned "Orientations are relative to one another, and when "-1" is supplied, it is understood that the reverse complement should be taken", but it is not still clear for me what do you mean. I would be appreciated if you can provide more details or example.

**Comment by ABignaud** [comment]
Hi Karimi,

The orientation column is effectively the orientation of the sequence relatively to the original sequence, and -1 means the reverse complement. However, here both fragments have an orientation of 1 meaning that they are kept as the original sequence.

The -1 in your file is the id_frag value. Before, instagraal scaffolding, a cleaning step is done to remove fragments of contig with low coverage (default with standard deviation below the mean). These fragments won't be given any id. Once, you launch the polishing, instagraal will correct its scaffold according to the initial contigs from the assembly (you can look at the [figure 4 of the paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02041-z/figures/4). In this step, it will also took back the removed fragments and give them an id of -1 which corresponds to the -1 in your example.

Your mitochondria size issue comes from your assembly as the initial contig (ptg000178) size is 32kb. During the scaffolding, the second fragments were removed, however at the polishing step the second fragment were just add to the first contig according to the original assembly.

Tell me if you need more details.
