### ISSUE TITLE
instagraal-polish: problem with -j option

### ISSUE THREAD

**Issue by MGautierINRA** [koszullab/instaGRAAL#29]
Dear maintainers,
I encountered a problem with _instagraal-polish_ when using the -j option which does not seem to work. Whatever the value given to the argument nothing is written at the junction of consecutive contigs in the obtained polished fasta file.
I am absolutely not an expert in python so I surely may have misunderstood most of the code but going through the _parse_info_frags.py_ script I noticed the argument "junction" argument in the write_fasta function is defined as a boolean, set by default to FALSE (L604), but when it is called with the "polishing mode" (L877), the given argument seems to be a string (resulting from the parsing L853). In addition within the code of the _write_fasta_  function, the _junction_ argument is considered either as a boolean (L644) or a string (L647 when given to the _Seq()_ function?)?
I think I found a trick to solve the problem for my own purpose by slightly modifying the code. It consist of making the -j argument ineffective by always using the _DEFAULT_JUNCTION_SEQUENCE_ (defined L33) between consecutive contig sequences within a scaffold with the two following slight modifications to the _parse_info_frags.py_ script:

**L646-L647 of the current version:**
                     _extra_seq = Seq(junction, IUPAC.ambiguous_dna)
                     current_seq = current_seq + extra_seq_
modified as follows:
                       _#extra_seq = Seq(junction, IUPAC.ambiguous_dna) 
                       current_seq = current_seq + DEFAULT_JUNCTION_SEQUENCE_ 

**L954 of the current version commented:**
          _#  junction=junction,_

Is it correct?
Many thanks for you help (and your programs!)
All the best

**Comment by nadegeguiglielmoni** [comment]
Hello,

Sorry for not answering to your issue earlier. We did fix this issue in the noopengl branch, and we need to do it for the master branch too.

Thank you for pointing it out.
