### ISSUE TITLE
pycuda._driver error

### ISSUE THREAD

**Issue by skumons** [koszullab/instaGRAAL#3]
Dear all, 
I'am sysadmin and I installed for one of my user the 'instagraal' program successfully but we get an error on the runtime.  I already tried to run with CUDA/9.2.28 without success and now with the CUDA/10.0.130 and kernel update, it's also failed (on the runtime)..

Here is my error:
instagraal graal_scaffolding_SRR3105481/ sim_c500_GCF_000002985.6_WBcel235_genomic.mixed.fa graal_14_n100_c1_N5 --debug
INFO :: Selected_device: Tesla V100-PCIE-16GB
Traceback (most recent call last):
  File "/opt/cecisw/arch/easybuild/2018b/software/Python/3.6.6-intel-2018b/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal')()
  File "/opt/sw/src/instagraal/instagraal/instagraal.py", line 2161, in main
    output_folder=output_folder,
  File "/opt/sw/src/instagraal/instagraal/instagraal.py", line 208, in __init__
    self.cuda_gl_init()
  File "/opt/sw/src/instagraal/instagraal/instagraal.py", line 1448, in cuda_gl_init
    curr_gpu, flags=cudagl.graphics_map_flags.NONE
pycuda._driver.Error: cuGLCtxCreate failed: unknown error

The pycuda versionis 2019.01 and GCC 7.3.0.

I have already lost a lot of time to build serveral version with success but all of my versions failed on the runtine with the same error 'pycuda._driver.Error: cuGLCtxCreate failed: unknown error'

Any idea ?

Thanks in advance,

Best Regards,
Sébastien.

**Comment by skumons** [comment]
Here is my nvidia-smi output:
Wed May 29 16:44:40 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   55C    P0    96W / 250W |    438MiB / 16130MiB |     50%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   39C    P0    27W / 250W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     60015      C   namd2                                        427MiB |
+-----------------------------------------------------------------------------+

**Comment by fabiengir** [comment]
Hello, 

We recently released a DockerFile for instagraal, I think it could solve your user problem. 

If error message concerning driver appears again, I think (if it's possible) you should update NVIDIA drivers. 

Let us know if it's helpfull, 

Best, 

Fabien G.
