### ISSUE TITLE
Instagraal docker run gives error about pyramid directory

### ISSUE THREAD

**Issue by alexvasilikop** [koszullab/instaGRAAL#32]
Hello,

I am trying to run the docker version of instagraal on an Ubuntu OS v. 18.10 linux machine.

the output of the command 
$nvidia-smi
is the following:
Tue Mar  1 13:22:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
| 36%   29C    P8     8W / 180W |     38MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31500      G   /usr/lib/xorg/Xorg                            26MiB |
+-----------------------------------------------------------------------------+

#######################################################################
The command 
$nvcc --version

gives the following output:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
(base) ➜  Brachionus_calyciflorus nvidia-smi

#################################################
The command
$ docker run --gpus all koszullab/instagraal instagraal --version

gives the output:
0.1.2
######################################################################
So I tried to run it like this:
$ docker run --gpus all koszullab/instagraal instagraal $outdir $genome $outdir2

The output:
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal')()
  File "/src/instagraal/instagraal/instagraal.py", line 1178, in main
    output_folder=output_folder,
  File "/src/instagraal/instagraal/instagraal.py", line 160, in __init__
    output_folder=output_folder,
  File "/src/instagraal/instagraal/simu_single.py", line 74, in __init__
    self.select_data_set(name)
  File "/src/instagraal/instagraal/simu_single.py", line 743, in select_data_set
    thresh_factor=self.thresh_factor,
  File "/src/instagraal/instagraal/pyramid_sparse.py", line 58, in build_and_filter
    os.mkdir(all_pyramid_folder)
FileNotFoundError: [Errno 2] No such file or directory: 'rejoined_polished.fasta.Hi-C_minimap2/pyramids'

Any help would be appreciated.
Thanks

**Comment by nadegeguiglielmoni** [comment]
Hello,

Have you checked this issue? https://github.com/koszullab/instaGRAAL/issues/24

**Comment by alexvasilikop** [comment]
Hi 
I think we have solved the problem for now thanks
