### ISSUE TITLE
Instagraal polish - KeyError

### ISSUE THREAD

**Issue by alexvasilikop** [koszullab/instaGRAAL#35]
Hello,

When I try to run instagraal polish post-scaffolding
instagraal-polish -m polishing -i info_frags.txt -o curated.fasta -f instagraal.fasta -j NNNNNNNNNN

I get the following error:

Appending the rest...
Traceback (most recent call last):
  File "/usr/local/bin/instagraal-polish", line 11, in <module>
    load_entry_point('instagraal', 'console_scripts', 'instagraal-polish')()
  File "/pycuda/src/instagraal/instagraal/parse_info_frags.py", line 949, in main
    output=output_file,
  File "/pycuda/src/instagraal/instagraal/parse_info_frags.py", line 645, in write_fasta
    seq_to_add = init_genome[init_contig][start:end]
KeyError: 'ctg000038'

I have tried this with several genomes so it seems to be not dataset dependent. I used the default info_frags.txt file from the instagraal output directory.

Thanks

**Comment by nadegeguiglielmoni** [comment]
Hello, 

For parameter -f you need to put the contigs as input, not the scaffolds. Scaffolding info is contained in info_frags.txt.

**Comment by alexvasilikop** [comment]
Great thanks, the problem is solved. Perhaps adding this info in the documentation would be helpful.

cheers
