### ISSUE TITLE
Error with --simple

### ISSUE THREAD

**Issue by hgdarras** [koszullab/instaGRAAL#40]
Dear all,

We observed the following error message while running instaGRAAL with the --simple flag.
Are we dealing with an installation or a data problem?

Thanks in advance for your help!
hugo

INFO :: mean size kb = 6.4507546267087275
INFO :: min fragment length =  0.073
INFO :: estimation of the parameters of the model
WARNING :: /usr/local/lib/python3.6/dist-packages/instagraal/optim_rippe_curve_update.py:47: RuntimeWarning: invalid value encountered in log
  + (d - 2) / ((np.power((lm * x / kuhn), 2) + d))

INFO :: p from estimate parameters  = [1.1178771257173667, 18.131529792453716, -1.0325689603584807, 2, 11697.042257632504]
INFO :: mean value trans = 0.03493796078866897
INFO :: BEWARE!!! : I will lower mean value trans  !!!
INFO :: estimate max dist cis trans = 50269.59680359397
(array([ 1.11787713e+00,  1.81315298e+01, -1.03256896e+00,  1.16970423e+04]), 1)
Traceback (most recent call last):
  File "/usr/local/bin/instagraal", line 11, in <module>
    load_entry_point('instagraal==0.1.6', 'console_scripts', 'instagraal')()
  File "/usr/local/lib/python3.6/dist-packages/instagraal/instagraal.py", line 1193, in main
    p2.simple_start(
AttributeError: 'instagraal_class' object has no attribute 'simple_start'`

**Comment by ABignaud** [comment]
Hi,

It seems to be a problem in the code, this feature is broken. I don't think we will correct it. If you want to run instagraal, just run it without this option.

**Comment by hgdarras** [comment]
Hi Amaury,

Thanks for the information.

Best
Hugo
