### ISSUE TITLE
pycuda installation

### ISSUE THREAD

**Issue by etiennejourdier** [koszullab/instaGRAAL#41]
Hi,
I'd like to use instaGRAAL on a Jupyter Notebook. The installation is correct except for pycuda: the last command ``sudo python3 setup.py install`` doesn't work because I don't have admin rights. Is there any other way of completing the pycuda installation without admin rights?
Thanks,
E.

**Comment by ABignaud** [comment]
Hi, 
I don't know a way to complete instagraal installation without admin rights. You can use it using the galaxy Europe server without installing it if you need. Locally, the easiest way to do it is to use the docker but it needs the admin rights too.
Amaury

**Comment by etiennejourdier** [comment]
Hi,
Thanks for the answer.
My jupyter server admin had the idea to compile pycuda, but we haven't tried it yet. 
And if not, yes, I will use the galaxy Europe server instead.
Best regards,
E.
