### ISSUE TITLE
Versions / Tags

### ISSUE THREAD

**Issue by lecorguille** [koszullab/instaGRAAL#8]
Hi,
Can you provide some more accurate version numbers both as github tags and docker tags, please?

I can see 
 - 0.1  https://github.com/koszullab/instaGRAAL/releases (7 days old)
 - 0.1.6 https://github.com/koszullab/instaGRAAL/blob/master/instagraal/version.py (13 mouths old)
 - 0.1.2 from your docker lastest (7 days old)
```
singularity pull docker://koszullab/instagraal
./instagraal_latest.sif instagraal --version
```

I have to deplay instaGRAAL on our infrastructure but I don't know which version

**Comment by cmdoret** [comment]
Hello !

Right, the release version was wrong. I've set it to 0.1.6 to match PyPi's version. I also triggered a new docker build, latest should now be 0.1.6.

Thanks for the notification :)
